### ISSUE TITLE
Explain the math abuse / document operator precedence

### ISSUE THREAD

**Issue by frostburn** [xenharmonic-devs/sonic-weave#86]
**34 53 63 65 72 80 87 104 111 311** — _Today at 12:33 AM_

> hmm i see... i would strongly suggest making some sort of rundown of all the potentially-unintuitive design choices in the programming language; this is the sort of info i'd want to know up-front

**frostburn** — _Today at 12:36 AM_

> Noted. I'll make a document explaining the rationale with mathematicians as the target audience and link it near the top of the user documentation.

**Comment by frostburn** [comment]
**34 53 63 65 72 80 87 104 111 311** — _Today at 12:40 AM_

> fwiw, the main things i am looking for when trying to do an appraisal of a programming language are:
> what are the operators? what is their precedence and associativity? what do they do? what are their potential pitfalls (for languages that arent strongly typed or use imprecise things like floats)? how do you express variables? what are the types? how do you make objects/classes and call methods?
> 
> those are like, the "bread and butter" of programming languages i think, then everything else is extra features like whether there's overload resolution or overload operating, whether there's inheritance or multiple inheritance, how you do library stuff, whether it's a functional language (meaning all functions are pure), whether it's compiled or interpreted (or both), etc.

**Comment by arseniiv** [comment]
So going down from [this line](https://github.com/xenharmonic-devs/sonic-weave/blob/5128c2d9d28c34ed9dd5c7be2499090fbc38f6dc/src/sonic-weave.pegjs#L473C1-L473C11) gives, from lowest to highest precedence

but first terms:
- *any-associative*: syntactically associates and means the same thing treated both as left- and right-associative;
- *bundle-associative*: syntactically associates but can’t be understood as left- or right-associative, instead it’s a vararg operation if the operator is the same (like `:` chords) or a bundle of operation pairs as with comparisons `==`, `<` etc.).

* `lest`: nonassociative
* `if`...`else`: nonassociative
* `??`, `and`, `or`: any(?)-associative (looks like the semantics allow to treat them as any associativity)
* relational:
  *  `===`, `!==`, `==`, `!=`, `<`, `<=`, `>`, `>=`: ideally bundle-associative having pairwise checks in conjunction
  * `of`, `not of`, `~of`, `not ~of`: left(?)-associative but ideally shouldn’t associate at all and it’s bad that they do
* chord builders:
  * '/`...`::`, `::`: non-associative
  * `:`: bundle-associative
* nedji / additive:
  * `+`, `-`, `to`, `by`, `max`, `min`, `/+`, `⊕`, `/-`, `⊖` and their `~`...`~` variants: left-associative
    * *might* be weird to have associativity for `to` and `by` or have them at this same level
  * `<`...`>`: postfix (nonassociative); weird that it means `x<2> + y<3>` shouldn’t parse
* `*`, `×`, `%`, `÷`, `\`, `mod`, `modc`, `rd`, `rdc`, `·`, `dot`, `⊗`, `tns` and their `~`...`~` variants: left-associative
* `--`, `-`, `- ~`, `%`, `% ~`, `÷`, `÷ ~`: prefix (nonassociative)
* `^/`, `^`, `/_`, `/^` and their `~`...`~` variants: right(?)-associative (I now finally see I don’t have a clue if it’s possible to tell right or left by the grammar)
  * a thing about logarithm having this precedence might be nonobvious

I’m leaving this at [this line](https://github.com/xenharmonic-devs/sonic-weave/blob/5128c2d9d28c34ed9dd5c7be2499090fbc38f6dc/src/sonic-weave.pegjs#L629) so far.

**Comment by arseniiv** [comment]
Adding weird/pathological cases or notes in no order:

- `2 + 1 min 3 - 4 max 5` is uncomfortable; I’d think `min` and `max` have lower precedence (higher in the list)
- also despite `and` and `or` mixing pretty well, I’m not sure `min` and `max` mix the same together (though logically it’s the same, a lattice structure, so ideally one should parse or not parse both equally)
- so, just to be sure it won’t be lost, check that `1 === 2 != 3 < 4` really translates into `(1 === 2) and (2 != 3) and (3 < 4)`
- in principle, `1 of [2,3] of [[1,2],[1,3],[2,3]]` really can work but it still stands that those can be misused
- be sure power operators are not left-associative without due cause: if one can’t go right-associative way then it should probably be nonassociative

**Comment by arseniiv** [comment]
About making operators clearer:

In the table

| Name                   | Linear         | Result   | Logarithmic      | Result     |
| ---------------------- | -------------- | -------- | ---------------- | ---------- |
| Val product            | `12@ · 3/2`    | `7`      | `<12 19] dot P5` | `7`        |

Right now it’s not clear if one can use `⋅` with logarithmic operands and `dot` with linear operands (and that they do the same in those cases). For some operators it ends up clear from context but for some it isn’t. I suggest just adding rows duplicating the same with other synonyms.

Then when precedence is dumped out in the readme and this is okay, I think I had a third PoI related to all this but I forgot it.

Also the rationale might start with “there are two domains because we wanted integers and rationals to be valid intervals without any coercion, and their operations to work in the usual way, so…” and also that `%` is because rational intervals are so omnipresent, this right at the start somewhere because I think it’s important to tell while the reader’s attention is still young.

**Comment by frostburn** [comment]
Thanks for digging through the grammar. Seeing it laid out like that helped in making it more sensible. Sorry for obsoleting your list so quickly but it was valuable work. :heart:

**Comment by arseniiv** [comment]
Well as the changes are for the better, I have no hurt feelings of any sort. (I don’t know how it works in the brain but it’s a boon because I get frustrated by other things that shouldn’t really affect me ideally.) And yeah it was a useful work that I took on myself and hopefully didn’t miss anything glaring, and if not then I’m very much satisfied with the result too.
